#!/usr/bin/env python3
"""Generate the LaTeX tables and figure data of the RQ1 results section.

Torch-free. Reads only stored artifacts:
  thesis_results/fullspace_ledger.csv                 search results (E0-E3, J12)
  results/exact_replays/replay_20261008/replay_results.csv   replays
  thesis_results/datalab_raw/.../final_candidate.json  final masks and bit-widths
  results/sequential_search_runs.csv                  screening protocol

Writes one .tex fragment per table/figure into --out (the thesis repository's
generated/rq1 directory). Every number in the fragments comes from these files.
"""

from __future__ import annotations

import argparse
import csv
import statistics as st
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.plan_exact_replays import FULLSPACE_CANDIDATES  # noqa: E402
from src.exact_replay import layer_index, load_final_candidate, module_is_active  # noqa: E402

REPLAY = REPO_ROOT / "results/exact_replays/replay_20261008/replay_results.csv"
LEDGER = REPO_ROOT / "thesis_results/fullspace_ledger.csv"
SCREEN = REPO_ROOT / "results/sequential_search_runs.csv"
SEEDS = (0, 1, 2)
ACTIVE = {0.0: 6_979_321_856, 0.125: 6_106_906_624, 0.25: 5_234_491_392}
AVG_BITS = {0.0: "3.000", 0.125: "3.464", 0.25: "4.083"}
HEADER = "% Generated by evopress/scripts/thesis_rq1_tables.py. Do not edit by hand.\n"


def num(x, d=2):
    return f"{x:.{d}f}"


def ms(values, d=2):
    if len(values) == 1:
        return num(values[0], d)
    return f"{num(st.mean(values), d)} $\\pm$ {num(st.pstdev(values), d)}"


def thousands(n):
    return f"{n:,}".replace(",", "{,}")


def load_inputs():
    ledger = list(csv.DictReader(open(LEDGER, encoding="utf-8")))
    replay = {r["id"]: r for r in csv.DictReader(open(REPLAY, encoding="utf-8"))}
    return ledger, replay


def ledger_values(ledger, condition, key):
    return [float(r[key]) for r in ledger if r["condition"] == condition and r[key] not in ("", None)]


def replay_values(replay, ids, key):
    return [float(replay[i][key]) for i in ids]


def write(out: Path, name: str, text: str):
    (out / name).write_text(HEADER + text, encoding="utf-8")


# ---------------------------------------------------------------------------


def table_reference(out, ledger, replay):
    e2 = [r for r in ledger if r["condition"] == "E2_quant_only_g150"]
    lines = [
        r"\begin{tabular}{@{}lrrr@{}}", r"\toprule",
        r"Model & WikiText-2 & C4 & Calib.\ KL \\", r"\midrule",
        r"Dense, 16-bit (E0) & 4.83 & 7.71 & -- \\",
        f"Uniform 3-bit (E1) & {num(float(replay['own_uniform3']['wikitext2_ppl']), 3)} & "
        f"{num(float(replay['own_uniform3']['c4_ppl']), 3)} & {num(float(replay['own_uniform3']['calibration_kl']), 4)} \\\\",
    ]
    for r in sorted(e2, key=lambda r: r["seed"]):
        lines.append(f"E2, seed {r['seed']} & {num(float(r['wikitext2_ppl']), 3)} & "
                     f"{num(float(r['c4_ppl']), 3)} & {num(float(r['final_calibration_kl']), 4)} \\\\")
    lines += [
        r"\midrule",
        f"E2, mean $\\pm$ SD & {ms([float(r['wikitext2_ppl']) for r in e2], 3)} & "
        f"{ms([float(r['c4_ppl']) for r in e2], 3)} & {ms([float(r['final_calibration_kl']) for r in e2], 4)} \\\\",
        r"\bottomrule", r"\end{tabular}",
    ]
    write(out, "tab_reference.tex", "\n".join(lines) + "\n")


def sparsity_rows(ledger, replay):
    """(s, label, W2 values, C4 values, KL values) for the main comparison."""
    e1 = replay["own_uniform3"]
    return [
        (0.0, "Uniform 3-bit (E1)", [float(e1["wikitext2_ppl"])], [float(e1["c4_ppl"])], [float(e1["calibration_kl"])]),
        (0.0, "Quant.-only search (E2)", ledger_values(ledger, "E2_quant_only_g150", "wikitext2_ppl"),
         ledger_values(ledger, "E2_quant_only_g150", "c4_ppl"), ledger_values(ledger, "E2_quant_only_g150", "final_calibration_kl")),
        (0.125, "Joint search (J12)", ledger_values(ledger, "joint_s0125_g150", "wikitext2_ppl"),
         ledger_values(ledger, "joint_s0125_g150", "c4_ppl"), ledger_values(ledger, "joint_s0125_g150", "final_calibration_kl")),
        (0.25, "Joint search (E3)", ledger_values(ledger, "E3_joint_s025_standard_g150", "wikitext2_ppl"),
         ledger_values(ledger, "E3_joint_s025_standard_g150", "c4_ppl"),
         ledger_values(ledger, "E3_joint_s025_standard_g150", "final_calibration_kl")),
    ]


def table_main(out, ledger, replay):
    lines = [
        r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule",
        r"Model & $s$ & Avg.\ bits & WikiText-2 & C4 & Calib.\ KL \\", r"\midrule",
    ]
    for s, label, w2, c4, kl in sparsity_rows(ledger, replay):
        lines.append(f"{label} & {s:g} & {AVG_BITS[s]} & {ms(w2, 3)} & {ms(c4, 3)} & {ms(kl, 4)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_main.tex", "\n".join(lines) + "\n")


def figure_sparsity(out, ledger, replay):
    """pgfplots: per-seed points and mean line for W2 and C4 against s."""
    rows = sparsity_rows(ledger, replay)
    searched = [rows[1], rows[2], rows[3]]
    parts = []
    for metric, idx, ymin, ymax, dense, uniform in (("WikiText-2", 2, 4, 10, 4.83, rows[0][2][0]),
                                                    ("C4", 3, 7, 13.5, 7.71, rows[0][3][0])):
        points = " ".join(f"({s:g},{v:.4f})" for s, _, *vals in searched for v in vals[idx - 2])
        means = " ".join(f"({s:g},{st.mean(vals[idx - 2]):.4f})" for s, _, *vals in searched)
        parts.append(
            "\\begin{axis}[rq1sparsity, ylabel={%s perplexity}, ymin=%s, ymax=%s]\n"
            "  \\addplot[thesisblue, thick, mark=none] coordinates {%s};\n"
            "  \\addplot[only marks, mark=o, thesisblue, mark size=2pt] coordinates {%s};\n"
            "  \\addplot[gray, dashed, domain=-0.02:0.27] {%s} node[pos=0.62, above, font=\\scriptsize, text=gray] {dense};\n"
            "  \\addplot[thesisorange, dashed, domain=-0.02:0.27] {%s} node[pos=0.62, above, font=\\scriptsize] {uniform 3-bit};\n"
            "\\end{axis}\n" % (metric, ymin, ymax, means, points, dense, uniform)
        )
    write(out, "fig_sparsity_w2.tex", parts[0])
    write(out, "fig_sparsity_c4.tex", parts[1])


def table_decomposition(out, ledger, replay):
    e2 = ledger_values(ledger, "E2_quant_only_g150", "wikitext2_ppl")
    e2c = ledger_values(ledger, "E2_quant_only_g150", "c4_ppl")
    rows = [(0.0, 4.83, 7.71, 4.83, 7.71, st.mean(e2), st.mean(e2c))]
    for s, fam, cond in ((0.125, "J12", "joint_s0125_g150"), (0.25, "E3", "E3_joint_s025_standard_g150")):
        f16w = replay_values(replay, [f"fp16_{fam}s{i}" for i in SEEDS], "wikitext2_ppl")
        f16c = replay_values(replay, [f"fp16_{fam}s{i}" for i in SEEDS], "c4_ppl")
        rows.append((s, 4.83, 7.71, st.mean(f16w), st.mean(f16c),
                     st.mean(ledger_values(ledger, cond, "wikitext2_ppl")), st.mean(ledger_values(ledger, cond, "c4_ppl"))))
    lines = [
        r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule",
        r"& \multicolumn{3}{c}{WikiText-2 perplexity} & \multicolumn{2}{c}{Increase} \\",
        r"\cmidrule(lr){2-4}\cmidrule(l){5-6}",
        r"$s$ & Dense & Mask, 16-bit & Mask, at $T$ & Removal & Quantization \\", r"\midrule",
    ]
    for s, dw, dc, fw, fc, tw, tc in rows:
        lines.append(f"{s:g} & {num(dw)} & {num(fw)} & {num(tw)} & {num(fw - dw)} & {num(tw - fw)} \\\\")
    lines += [r"\midrule", r"& \multicolumn{3}{c}{C4 perplexity} & & \\", r"\midrule"]
    for s, dw, dc, fw, fc, tw, tc in rows:
        lines.append(f"{s:g} & {num(dc)} & {num(fc)} & {num(tc)} & {num(fc - dc)} & {num(tc - fc)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_decomposition.tex", "\n".join(lines) + "\n")


def smart(v, d=2):
    if v >= 1000:
        return f"{v:,.0f}".replace(",", "{,}")
    if v >= 100:
        return f"{v:.1f}"
    return f"{v:.{d}f}"


def fmt_range(values, d=2):
    if len(values) > 1 and max(values) > 3 * min(values):
        return " / ".join(smart(v, d) for v in values)
    if len(values) == 1:
        return smart(values[0], d)
    return ms(values, d)


def spread(values):
    return len(values) > 1 and max(values) > 3 * min(values)


def baseline_rows(label, ids, r):
    """One row with mean +- SD, or one row per mask if a metric differs by more than 3x."""
    w2, c4, kl = r(ids, "wikitext2_ppl"), r(ids, "c4_ppl"), r(ids, "calibration_kl")
    if spread(w2) or spread(c4) or spread(kl):
        base = label.replace("masks (3)", "mask")
        return [f"{base} {i + 1} & {smart(a)} & {smart(b)} & {smart(c, 3)} \\\\"
                for i, (a, b, c) in enumerate(zip(w2, c4, kl))]
    return [f"{label} & {fmt_range(w2)} & {fmt_range(c4)} & {fmt_range(kl, 3)} \\\\"]


def table_baselines(out, ledger, replay):
    def r(ids, key):
        return replay_values(replay, ids, key)

    groups = [
        (0.125, "Joint search (J12)", [f"own_J12s{i}" for i in SEEDS]),
        (0.125, "Joint masks, E2 profile shifted", [f"att_J12s{i}_QE2s{i}_shift" for i in SEEDS]),
        (0.125, "Joint masks, near-uniform", [f"att_J12s{i}_nu" for i in SEEDS]),
        (0.125, "Block-influence mask", ["h12_bi_score_nu"]),
        (0.125, "Random masks (3)", [f"h12_random_s{i}_nu" for i in SEEDS]),
        (0.125, "Last sublayers", ["h12_late_layer_nu"]),
        (0.125, "Last sublayers before the final layer", ["h12_late_layer_keep_last_nu"]),
        (0.25, "Joint search (E3)", [f"own_E3s{i}" for i in SEEDS]),
        (0.25, "Joint masks, E2 profile shifted", [f"att_E3s{i}_QE2s{i}_shift" for i in SEEDS]),
        (0.25, "Joint masks, near-uniform", [f"att_E3s{i}_nu" for i in SEEDS]),
        (0.25, "Depth-only masks, E2 profile shifted", [f"ind_DO25s{i}_QE2s{i}_shift" for i in SEEDS]),
        (0.25, "Depth-only masks, near-uniform", [f"ind_DO25s{i}_nu" for i in SEEDS]),
        (0.25, "Block-influence mask", ["h25_bi_score_nu"]),
        (0.25, "Random masks (3)", [f"h25_random_s{i}_nu" for i in SEEDS]),
        (0.25, "Last sublayers", ["h25_late_layer_nu"]),
        (0.25, "Last sublayers before the final layer", ["h25_late_layer_keep_last_nu"]),
    ]
    lines = [
        r"\begin{tabular}{@{}>{\raggedright\arraybackslash}p{55mm}rrr@{}}", r"\toprule",
        r"Configuration & WikiText-2 & C4 & Calib.\ KL \\",
    ]
    current = None
    for s, label, ids in groups:
        if s != current:
            lines += [r"\midrule", f"\\multicolumn{{4}}{{@{{}}l}}{{\\emph{{$s = {s:g}$}}}} \\\\"]
            current = s
        lines += baseline_rows(label, ids, r)
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_baselines.tex", "\n".join(lines) + "\n")

    f16 = [
        (0.125, "Joint masks (J12)", [f"fp16_J12s{i}" for i in SEEDS]),
        (0.125, "Block-influence mask", ["fp16_h12_bi_score"]),
        (0.125, "Last sublayers before the final layer", ["fp16_h12_late_layer_keep_last"]),
        (0.25, "Joint masks (E3)", [f"fp16_E3s{i}" for i in SEEDS]),
        (0.25, "Depth-only masks", [f"fp16_DO25s{i}" for i in SEEDS]),
        (0.25, "Block-influence mask", ["fp16_h25_bi_score"]),
        (0.25, "Last sublayers before the final layer", ["fp16_h25_late_layer_keep_last"]),
    ]
    lines = [r"\begin{tabular}{@{}>{\raggedright\arraybackslash}p{55mm}rrr@{}}", r"\toprule",
             r"Mask (16-bit, not at $T$) & WikiText-2 & C4 & Calib.\ KL \\"]
    current = None
    for s, label, ids in f16:
        if s != current:
            lines += [r"\midrule", f"\\multicolumn{{4}}{{@{{}}l}}{{\\emph{{$s = {s:g}$}}}} \\\\"]
            current = s
        lines += baseline_rows(label, ids, r)
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_fp16.tex", "\n".join(lines) + "\n")


def table_allocation_per_seed(out, replay):
    lines = [
        r"\begin{tabular}{@{}lrrrrrr@{}}", r"\toprule",
        r"& \multicolumn{3}{c}{WikiText-2 perplexity} & \multicolumn{3}{c}{Calibration KL} \\",
        r"\cmidrule(lr){2-4}\cmidrule(l){5-7}",
        r"Mask & Own & E2 shifted & Near-unif. & Own & E2 shifted & Near-unif. \\", r"\midrule",
    ]
    for fam in ("J12", "E3"):
        for i in SEEDS:
            ids = [f"own_{fam}s{i}", f"att_{fam}s{i}_QE2s{i}_shift", f"att_{fam}s{i}_nu"]
            w = [float(replay[x]["wikitext2_ppl"]) for x in ids]
            k = [float(replay[x]["calibration_kl"]) for x in ids]
            lines.append(f"{fam} seed {i} & " + " & ".join(num(v, 3) for v in w) + " & "
                         + " & ".join(num(v, 4) for v in k) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_allocation_swap.tex", "\n".join(lines) + "\n")


TYPES = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]


def table_bits_by_type(out):
    lines = [
        r"\begin{tabular}{@{}lrrrrrrrr@{}}", r"\toprule",
        r"Search & \texttt{q} & \texttt{k} & \texttt{v} & \texttt{o} & \texttt{gate} & \texttt{up} & \texttt{down} & All active \\",
        r"\midrule",
    ]
    for fam, label, s in (("E2", "Quantization-only (E2), $s = 0$", 0.0), ("J12", "Joint (J12), $s = 0.125$", 0.125),
                          ("E3", "Joint (E3), $s = 0.25$", 0.25)):
        per_type = {t: [] for t in TYPES}
        for i in SEEDS:
            cand = load_final_candidate(REPO_ROOT / FULLSPACE_CANDIDATES[f"{fam}s{i}"])
            for t in TYPES:
                vals = [b for n, b in cand["bits"].items() if n.endswith(t) and module_is_active(n, cand["drop"])]
                per_type[t].append(st.mean(vals))
        lines.append(label + " & " + " & ".join(num(st.mean(per_type[t])) for t in TYPES) + f" & {AVG_BITS[s]} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_bits_by_type.tex", "\n".join(lines) + "\n")


def figure_removals(out):
    """TikZ grid: number of seeds (0-3) removing each sublayer, for J12 and E3."""
    cell, pitch, row_h = 0.30, 0.32, 0.42
    blocks = []
    tops = {"J12": 0.0, "E3": -1.35}
    for fam, top in tops.items():
        counts = {"attn": [0] * 32, "mlp": [0] * 32}
        for i in SEEDS:
            cand = load_final_candidate(REPO_ROOT / FULLSPACE_CANDIDATES[f"{fam}s{i}"])
            for kind in counts:
                for j in range(32):
                    counts[kind][j] += int(cand["drop"][kind][j])
        label = "$s = 0.125$ (J12)" if fam == "J12" else "$s = 0.25$ (E3)"
        blocks.append(f"\\node[anchor=south west, font=\\footnotesize, inner sep=1pt] at (0,{top + 0.04:.2f}) {{{label}}};")
        for r, kind in enumerate(("attn", "mlp")):
            y = top - r * row_h
            name = "attention" if kind == "attn" else "MLP"
            blocks.append(f"\\node[anchor=east, font=\\scriptsize] at (-0.05,{y - 0.19:.2f}) {{{name}}};")
            for j, c in enumerate(counts[kind]):
                shade = {0: "white", 1: "thesisblue!25", 2: "thesisblue!60", 3: "thesisblue"}[c]
                blocks.append(f"\\fill[{shade}] ({j * pitch:.2f},{y:.2f}) rectangle ++({cell},-0.38);")
            blocks.append(f"\\draw[gray!60] (0,{y:.2f}) rectangle ({32 * pitch - 0.02:.2f},{y - 0.38:.2f});")
    bottom = tops["E3"] - row_h - 0.38
    for j in (0, 4, 8, 12, 16, 20, 24, 28, 31):
        blocks.append(f"\\node[font=\\scriptsize, anchor=north] at ({j * pitch + cell / 2:.2f},{bottom - 0.02:.2f}) {{{j}}};")
    blocks.append(f"\\node[font=\\scriptsize, anchor=north] at ({16 * pitch:.2f},{bottom - 0.32:.2f}) {{decoder layer}};")
    legend_y = bottom - 0.85
    blocks.append(f"\\node[anchor=west, font=\\scriptsize] at (0,{legend_y - 0.15:.2f}) "
                  "{Number of seeds that remove the sublayer:};")
    x = 6.4
    for c, shade in ((0, "white"), (1, "thesisblue!25"), (2, "thesisblue!60"), (3, "thesisblue")):
        blocks.append(f"\\filldraw[fill={shade}, draw=gray!60] ({x:.2f},{legend_y:.2f}) rectangle ++(0.30,-0.30);")
        blocks.append(f"\\node[anchor=west, font=\\scriptsize] at ({x + 0.32:.2f},{legend_y - 0.15:.2f}) {{{c}}};")
        x += 1.0
    write(out, "fig_removals.tex", "\n".join(blocks) + "\n")


def table_screening(out):
    rows = list(csv.DictReader(open(SCREEN, encoding="utf-8")))
    by = {}
    for r in rows:
        by.setdefault(r["method"], []).append(float(r["wikitext2_ppl"]))
    spec = [
        ("depth_uniform", "Depth-only mask, uniform 3-bit \\texttt{q\\_proj}", "572"),
        ("independent", "Depth-only mask $+$ quantization-only profile", "$2 \\times 572$"),
        ("seq_depth_to_quant_frozen", "Structure $\\rightarrow$ quantization, frozen mask", "1{,}113"),
        ("seq_quant_to_depth_frozen", "Quantization $\\rightarrow$ structure, frozen bit-widths", "1{,}144"),
        ("joint_g20", "Joint search, $G = 20$", "572"),
        ("joint_g50", "Joint search, $G = 50$", "1{,}382"),
    ]
    lines = [r"\begin{tabular}{@{}>{\raggedright\arraybackslash}p{74mm}rl@{}}", r"\toprule",
             r"Method (screening protocol, $s = 0.25$) & Evaluations & WikiText-2 \\", r"\midrule"]
    for key, label, evals in spec:
        vals = by[key]
        lines.append(f"{label} & {evals} & {ms(vals, 2)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_screening.tex", "\n".join(lines) + "\n")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", required=True)
    args = parser.parse_args(argv)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    ledger, replay = load_inputs()
    table_reference(out, ledger, replay)
    table_main(out, ledger, replay)
    figure_sparsity(out, ledger, replay)
    table_decomposition(out, ledger, replay)
    table_baselines(out, ledger, replay)
    table_allocation_per_seed(out, replay)
    table_bits_by_type(out)
    figure_removals(out)
    table_screening(out)
    print(f"wrote {sorted(p.name for p in out.iterdir())}")


if __name__ == "__main__":
    main()
