#!/usr/bin/env python3
"""Generate the LaTeX tables and figure data of thesis Section 6.3 (RQ2).

Inputs (all in this repository): ``thesis_results/fullspace_ledger.csv`` (final
metrics of the full-space runs), the generation logs in
``thesis_results/datalab_raw/`` (convergence, effort, operator diagnostics) and
the run summaries of the screening runs in ``results/runs/`` and
``thesis_results/datalab_raw/cheap_population_crossover/``.

Usage: python scripts/thesis_rq2_tables.py --out <thesis>/generated/rq2
"""

from __future__ import annotations

import argparse
import csv
import json
import statistics as st
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RAW = REPO / "thesis_results/datalab_raw"
LEDGER = REPO / "thesis_results/fullspace_ledger.csv"

# Full-space runs at s = 0.25 (and J12 for the horizon table). Resumed runs list
# their attempts in order; rows are merged and deduplicated by generation.
RUNS = {
    "E3s0": ["paper_matched/joint/joint_seed0_attempt1_20260831"],
    "E3s1": ["paper_matched/joint/joint_seed1_attempt1_20260901",
             "paper_matched/joint/joint_seed1_attempt2_resume_20260901",
             "paper_matched/joint/joint_seed1_attempt3_resume_20260902"],
    "E3s2": ["paper_matched/joint/joint_seed2_attempt1_20260903"],
    **{f"IAs{i}": [f"fullspace_extensions/fullspace_joint_s025_ia_g150_seed{i}_attempt1"] for i in range(3)},
    "DWs0": ["fullspace_extensions/fullspace_depthwarm_g150_seed0_attempt1"],
    **{f"P4s{i}": [f"fullspace_extensions/fullspace_joint_s025_pop4_g150_seed{i}_attempt1"] for i in range(2)},
    "LXs0": ["fullspace_extensions/fullspace_joint_s025_localxover_pop4_g150_seed0_attempt1"],
    **{f"J12s{i}": [f"fullspace_extensions/fullspace_joint_s0125_g150_seed{i}_attempt1"] for i in range(3)},
}
LEDGER_CONDITION = {
    "E3": "E3_joint_s025_standard_g150", "IA": "joint_s025_ia_g150", "DW": "depthwarm_g150",
    "P4": "joint_s025_pop4_g150", "LX": "joint_s025_localxover_pop4_g150", "J12": "joint_s0125_g150",
}
VARIANT_LABEL = {
    "E3": "Standard (E3)", "IA": "Interaction-aware (IA)", "DW": "Warm start (DW)",
    "P4": "Population (P4)", "LX": "Crossover (LX)",
}
RESUMED = {"E3s1": "3 attempts", "P4s0": "resumed at $G = 18$"}
SEEDS = {"E3": [0, 1, 2], "IA": [0, 1, 2], "DW": [0], "P4": [0, 1], "LX": [0]}


def fmt(x, d=3):
    return f"{x:.{d}f}"


def ms(values, d=3):
    if len(values) == 1:
        return fmt(values[0], d)
    return f"{fmt(st.mean(values), d)} $\\pm$ {fmt(st.pstdev(values), d)}"


def signed(x, d=3):
    return ("$+$" if x >= 0 else "$-$") + fmt(abs(x), d)


def write(out: Path, name: str, text: str) -> None:
    out.mkdir(parents=True, exist_ok=True)
    header = "% Generated by evopress/scripts/thesis_rq2_tables.py. Do not edit by hand.\n"
    (out / name).write_text(header + text, encoding="utf-8")


def ledger() -> dict[str, dict[str, float]]:
    out = {}
    names = {v: k for k, v in LEDGER_CONDITION.items()}
    for row in csv.DictReader(LEDGER.open(encoding="utf-8")):
        if row["condition"] in names:
            out[f"{names[row['condition']]}s{row['seed']}"] = {
                "w2": float(row["wikitext2_ppl"]), "c4": float(row["c4_ppl"]),
                "kl": float(row["final_calibration_kl"]), "evals": int(row["candidate_evaluations"]),
                "tokens": int(row["search_tokens"]),
            }
    return out


def generation_rows(label: str) -> list[dict[str, str]]:
    by_gen: dict[int, dict[str, str]] = {}
    for rel in RUNS[label]:
        for row in csv.DictReader((RAW / rel / "generation_log.csv").open(encoding="utf-8")):
            by_gen[int(row["generation"])] = row  # later rows (attempts) win; removes duplicates
    gens = sorted(by_gen)
    if gens != list(range(1, gens[-1] + 1)):
        raise ValueError(f"{label}: generations are not contiguous")
    return [by_gen[g] for g in gens]


def tokens_before(rows, g: int) -> int:
    """Evaluated tokens after g - 1 generations (initial evaluation included)."""
    if g == 1:
        first = rows[0]
        per_gen = sum(int(first[f"evaluation_tokens_stage_{s}"]) for s in (1, 2, 3))
        return int(first["evaluation_tokens_search_cumulative"]) - per_gen
    return int(rows[g - 2]["evaluation_tokens_search_cumulative"])


# ---------------------------------------------------------------------------
# Full-space tables.
# ---------------------------------------------------------------------------


def table_variants(out, L):
    lines = [
        r"\begin{tabular}{@{}llrrrrr@{}}", r"\toprule",
        r"& & & & & \multicolumn{2}{c}{Difference to E3} \\", r"\cmidrule(l){6-7}",
        r"Variant & Seed & WikiText-2 & C4 & Calib.\ KL & WikiText-2 & Calib.\ KL \\", r"\midrule",
    ]
    for code in ("E3", "IA", "DW", "P4", "LX"):
        seeds = SEEDS[code]
        for k, seed in enumerate(seeds):
            r = L[f"{code}s{seed}"]
            ref = L[f"E3s{seed}"]
            first = VARIANT_LABEL[code] if k == 0 else ""
            diff = ("--", "--") if code == "E3" else (signed(r["w2"] - ref["w2"]), signed(r["kl"] - ref["kl"], 4))
            lines.append(f"{first} & {seed} & {fmt(r['w2'])} & {fmt(r['c4'])} & {fmt(r['kl'], 4)} & {diff[0]} & {diff[1]} \\\\")
        if len(seeds) == 3:
            vals = [L[f"{code}s{s}"] for s in seeds]
            w2d = [L[f"{code}s{s}"]["w2"] - L[f"E3s{s}"]["w2"] for s in seeds]
            kld = [L[f"{code}s{s}"]["kl"] - L[f"E3s{s}"]["kl"] for s in seeds]
            diff = ("", "") if code == "E3" else (signed(st.mean(w2d)), signed(st.mean(kld), 4))
            lines.append(f"& mean & {ms([v['w2'] for v in vals])} & {ms([v['c4'] for v in vals])} & "
                         f"{ms([v['kl'] for v in vals], 4)} & {diff[0]} & {diff[1]} \\\\")
        lines.append(r"\addlinespace")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    write(out, "tab_variants.tex", "\n".join(lines) + "\n")


def horizon_values(L):
    rows = {}
    for label in [f"{c}s{s}" for c in ("E3", "IA", "DW", "P4", "LX") for s in SEEDS[c]] + ["J12s0", "J12s1", "J12s2"]:
        log = generation_rows(label)
        g21 = log[20]  # held-out diagnostics of generation 21 evaluate the best candidate after 20 generations
        rows[label] = {
            "w2_20": float(g21["wikitext2_ppl"]), "c4_20": float(g21["c4_ppl"]),
            "w2_150": L[label]["w2"], "c4_150": L[label]["c4"],
            "fit_20": float(log[19]["best_search_fitness"]), "fit_150": float(log[149]["best_search_fitness"]),
        }
    return rows


def table_horizon(out, H):
    lines = [
        r"\begin{tabular}{@{}llrrrr@{}}", r"\toprule",
        r"& & \multicolumn{2}{c}{WikiText-2} & \multicolumn{2}{c}{C4} \\",
        r"\cmidrule(lr){3-4}\cmidrule(l){5-6}",
        r"Variant & Seed & $G = 20$ & $G = 150$ & $G = 20$ & $G = 150$ \\", r"\midrule",
    ]
    order = [("E3", SEEDS["E3"]), ("IA", SEEDS["IA"]), ("DW", [0]), ("P4", [0, 1]), ("LX", [0])]
    for code, seeds in order:
        for k, s in enumerate(seeds):
            h = H[f"{code}s{s}"]
            name = code if k == 0 else ""
            lines.append(f"{name} & {s} & {fmt(h['w2_20'])} & {fmt(h['w2_150'])} & {fmt(h['c4_20'])} & {fmt(h['c4_150'])} \\\\")
    lines.append(r"\midrule")
    for k, s in enumerate((0, 1, 2)):
        h = H[f"J12s{s}"]
        lines.append(f"{'J12 ($s = 0.125$)' if k == 0 else ''} & {s} & {fmt(h['w2_20'])} & {fmt(h['w2_150'])} & "
                     f"{fmt(h['c4_20'])} & {fmt(h['c4_150'])} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_horizon.tex", "\n".join(lines) + "\n")


def figure_convergence(out, L):
    """pgfplots series: held-out WikiText-2 and best search fitness vs evaluated tokens."""
    series = {"E3": SEEDS["E3"], "IA": SEEDS["IA"], "DW": [0], "P4": [0, 1], "LX": [0]}
    style = {
        "E3": "thesisblue, thick", "IA": "thesisorange, thick", "DW": "thesisaqua, thick",
        "P4": "black!65, thick, densely dashed", "LX": "violet, thick, densely dotted",
    }
    legend = {"E3": "E3 (3 seeds)", "IA": "IA (3 seeds)", "DW": "DW (seed 0)", "P4": "P4 (2 seeds)", "LX": "LX (seed 0)"}
    w2_parts, fit_parts = [], []
    for code, seeds in series.items():
        logs = {s: generation_rows(f"{code}s{s}") for s in seeds}
        pts_w2, pts_fit = [], []
        for g in range(11, 150, 5):  # held-out diagnostics at generations 1, 6, 11, ...; start after 10 generations
            x = st.mean(tokens_before(logs[s], g) for s in seeds) / 1e6
            y = st.mean(float(logs[s][g - 1]["wikitext2_ppl"]) for s in seeds)
            pts_w2.append(f"({x:.2f},{y:.4f})")
        x_end = st.mean(L[f"{code}s{s}"]["tokens"] for s in seeds) / 1e6
        pts_w2.append(f"({x_end:.2f},{st.mean(L[f'{code}s{s}']['w2'] for s in seeds):.4f})")
        for g in range(5, 151, 5):
            x = st.mean(int(logs[s][g - 1]["evaluation_tokens_search_cumulative"]) for s in seeds) / 1e6
            y = st.mean(float(logs[s][g - 1]["best_search_fitness"]) for s in seeds)
            pts_fit.append(f"({x:.2f},{y:.4f})")
        w2_parts.append(f"\\addplot[{style[code]}, mark=none] coordinates {{{' '.join(pts_w2)}}};")
        fit_parts.append(f"\\addplot[{style[code]}, mark=none] coordinates {{{' '.join(pts_fit)}}};\n"
                         f"\\addlegendentry{{{legend[code]}}}")
    write(out, "fig_convergence_w2.tex", "\n".join(w2_parts) + "\n")
    write(out, "fig_convergence_fitness.tex", "\n".join(fit_parts) + "\n")


def operator_stats(label):
    rows = generation_rows(label)
    offspring, winners = Counter(), Counter()
    replaced = 0
    xo = Counter()
    for r in rows:
        summary = json.loads(r["mutation_summary"])
        for kind, n in summary.get("generated_offspring_by_type", {}).items():
            offspring[kind] += int(n)
        winners[r["selected_parent_mutation_type"]] += 1
        replaced += r["accepted_parent_replacement"] == "True"
        diag = summary.get("crossover_diagnostics") or {}
        for key in ("crossover_offspring_attempted", "crossover_duplicates", "crossover_no_legal_exchange",
                    "crossover_offspring", "crossover_infeasible_candidates"):
            xo[key] += int(diag.get(key) or 0)
    return {"gens": len(rows), "offspring": offspring, "winners": winners, "replaced": replaced, "xo": xo,
            "runtime_h": float(rows[-1]["runtime_seconds_cumulative"]) / 3600}


def table_operators(out):
    """Offspring by type, origin of the best candidate, and LX diagnostics."""
    kinds = ["depth", "quantization", "interaction_aware", "local exchange crossover"]
    lines = [
        r"\begin{tabular}{@{}lrrrrrrrrr@{}}", r"\toprule",
        r"& \multicolumn{4}{c}{Offspring per generation} & \multicolumn{5}{c}{Origin of the best candidate (generations)} \\",
        r"\cmidrule(lr){2-5}\cmidrule(l){6-10}",
        r"Run & S & Q & C & X & S & Q & C & X & kept \\",
        r"\midrule",
    ]
    for label in ("E3s0", "E3s1", "E3s2", "IAs0", "IAs1", "IAs2", "DWs0", "P4s0", "P4s1", "LXs0"):
        stats = operator_stats(label)
        n = stats["gens"]
        mix = [f"{stats['offspring'][k] / n:.0f}" if stats["offspring"][k] else "--" for k in kinds]
        w = stats["winners"]
        won = [str(w.get(k, 0)) if stats["offspring"][k] else "--" for k in kinds] + [str(w.get("parent", 0))]
        lines.append(f"{label[:-2]} s{label[-1]} & " + " & ".join(mix + won) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_operators.tex", "\n".join(lines) + "\n")
    lx = operator_stats("LXs0")["xo"]
    stats = {k: int(v) for k, v in lx.items()}
    (out / "lx_crossover_stats.json").write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")
    return stats


def table_cost(out, L):
    lines = [
        r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule",
        r"Variant & Seeds & Evaluations & Tokens & Search time (h) & h per $10^8$ tokens \\", r"\midrule",
    ]
    for code in ("E3", "IA", "DW", "P4", "LX"):
        seeds = SEEDS[code]
        hours = [operator_stats(f"{code}s{s}")["runtime_h"] for s in seeds]
        r = L[f"{code}s{seeds[0]}"]
        per = [h / (L[f"{code}s{s}"]["tokens"] / 1e8) for h, s in zip(hours, seeds)]
        hours_txt = ", ".join(f"{h:.1f}" + ("\\textsuperscript{a}" if f"{code}s{s}" in RESUMED else "")
                              for h, s in zip(hours, seeds))
        per_txt = f"{min(per):.1f}--{max(per):.1f}" if len(per) > 1 else f"{per[0]:.1f}"
        evals = f"{r['evals']:,}".replace(",", "{,}")
        lines.append(f"{code} & {len(seeds)} & {evals} & {r['tokens'] / 1e6:.1f}\\,M & {hours_txt} & {per_txt} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_cost.tex", "\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Screening table.
# ---------------------------------------------------------------------------

RUNS_ROOT = REPO / "results/runs"
CHEAP = RAW / "cheap_population_crossover"
SCREEN = [
    # (group, label, G, P, directory pattern with {s}, seeds)
    ("Reference", "Standard joint", 20, 1, RUNS_ROOT / "thesis_medium_joint_mistral_s0.25_qproj3.0_g20_o16_seed{s}", (0, 1, 2)),
    ("Reference", "Standard joint", 50, 1, RUNS_ROOT / "thesis_compute_matched_joint_mistral_s0.25_qproj3.0_g50_o16_seed{s}", (0, 1, 2)),
    ("Mutation", "Interaction-aware", 20, 1, RUNS_ROOT / "thesis_interactionaware_joint_mistral_s0.25_qproj3.0_g20_o16_seed{s}", (0, 1, 2)),
    ("Mutation", "Interaction-aware", 50, 1, RUNS_ROOT / "thesis_interactionaware_joint_mistral_s0.25_qproj3.0_g50_o16_seed{s}", (0, 1, 2)),
    ("Mutation", "Joint-aware, $p_{\\mathrm{ja}} = 0.5$", 50, 1, RUNS_ROOT / "thesis_jointaware_joint_mistral_s0.25_qproj3.0_g50_o16_seed{s}", (0, 1, 2)),
    ("Mutation", "Fixed strength, $k_{\\max} = 1$", 50, 1, RUNS_ROOT / "thesis_fixedstrength_joint_mistral_s0.25_qproj3.0_g50_o16_seed{s}", (0, 1, 2)),
    ("Initialization", "Structure $\\rightarrow$ joint, warm", 20, 1, RUNS_ROOT / "thesis_sequential_depth_to_joint_warm_mistral_s0.25_qproj3.0_g20_o16_seed{s}", (0, 1, 2)),
    ("Initialization", "Structure $\\rightarrow$ joint, warm", 50, 1, RUNS_ROOT / "thesis_depthwarm_standard_joint_mistral_s0.25_qproj3.0_g50_o16_seed{s}", (0, 1, 2)),
    ("Initialization", "Structure $\\rightarrow$ joint, warm, IA", 50, 1, RUNS_ROOT / "thesis_depthwarm_interactionaware_joint_mistral_s0.25_qproj3.0_g50_o16_seed{s}", (0, 1, 2)),
    ("Initialization", "Quantization $\\rightarrow$ joint, warm", 20, 1, RUNS_ROOT / "thesis_sequential_quant_to_joint_warm_mistral_s0.25_qproj3.0_g20_o16_seed{s}", (0, 1, 2)),
    ("Initialization", "Quantization $\\rightarrow$ joint, warm, IA", 20, 1, RUNS_ROOT / "thesis_sequential_quant_to_joint_warm_interactionaware_mistral_s0.25_qproj3.0_g20_o16_seed{s}", (0, 1, 2)),
    ("Population", "Population $P = 4$", 20, 4, CHEAP / "joint_g20_population_pop4_seed{s}", (0, 1, 2)),
    ("Population", "Population $P = 4$", 50, 4, CHEAP / "joint_g50_population_pop4_seed{s}", (0, 1, 2)),
    ("Population", "$P = 4$, component crossover", 20, 4, RUNS_ROOT / "thesis_component_crossover_mistral_s0.25_qproj3.0_g20_o16_p4_c025_seed{s}", (0, 1, 2)),
    ("Population", "$P = 4$, layer-bundle crossover", 20, 4, CHEAP / "joint_g20_layerbundle_xover_pop4_seed{s}", (0,)),
    ("Population", "$P = 4$, local-exchange crossover", 20, 4, CHEAP / "joint_g20_localexchange_xover_pop4_seed{s}", (0,)),
    ("Population", "$P = 4$, interaction-aware", 20, 4, CHEAP / "joint_g20_interactionaware_pop4_seed{s}", (0,)),
]


def screening_effort(G: int, P: int) -> tuple[int, int]:
    """Evaluations and tokens of the screening schedule (Eq. generation_cost)."""
    evals = 32 + G * (16 + 8 + 2 + P)
    tokens = 32 * 512 + G * (16 * 512 + 8 * 2048 + (2 + P) * 8192)
    return evals, tokens


def screening_values(pattern: Path, seeds) -> list[float]:
    values = []
    for s in seeds:
        path = Path(str(pattern).format(s=s)) / "run_summary.json"
        values.append(float(json.loads(path.read_text(encoding="utf-8"))["final_metrics"]["wikitext2_ppl"]))
    return values


def table_screening(out):
    ref = {G: screening_values(SCREEN[i][4], (0, 1, 2)) for i, G in ((0, 20), (1, 50))}
    lines = [
        r"\begin{tabular}{@{}>{\raggedright\arraybackslash}p{50mm}rrrrr@{}}", r"\toprule",
        r"Variant & $G$ & Evaluations & Tokens & WikiText-2 & Diff.\ to standard \\", r"\midrule",
        r"\multicolumn{6}{@{}l}{\emph{Mistral-7B, \texttt{q\_proj} scope, $s = 0.25$, $\lambda = 16$}} \\",
    ]
    group = None
    for grp, label, G, P, pattern, seeds in SCREEN:
        if grp != group:
            if group is not None:
                lines.append(r"\addlinespace")
            group = grp
        vals = screening_values(pattern, seeds)
        evals, tokens = screening_effort(G, P)
        ref_vals = [ref[G][s] for s in seeds]
        if grp == "Reference":
            diff = "--"
        else:
            d = st.mean(v - r for v, r in zip(vals, ref_vals))
            diff = signed(d, 2) + ("" if len(seeds) == 3 else f" (seed {seeds[0]})")
        val_txt = (f"{st.mean(vals):.2f} $\\pm$ {st.pstdev(vals):.2f}" if len(vals) == 3 else f"{vals[0]:.2f}")
        evals_txt = f"{evals:,}".replace(",", "{,}")
        lines.append(f"{label} & {G} & {evals_txt} & {tokens / 1e6:.2f}\\,M & {val_txt} & {diff} \\\\")
    # TinyLlama schedule screens (s = 0.125, lambda = 8): reported against the default (max-3) schedule.
    tiny = [
        ("Default ($k_{\\max} = 3$)", "screen_jointaware_tiny_p0_g20_o8"),
        ("Adaptive strength", "screen_adaptive_tiny_pat3_max3_g20_o8"),
        ("Fixed strength, $k_{\\max} = 1$", "screen_fixedstrength_tiny_max1_g20_o8"),
        ("Coarse-to-fine ($3 \\rightarrow 1$)", "screen_coarsetofine_tiny_s3_e1_g20_o8"),
        ("Joint-aware, $p_{\\mathrm{ja}} = 0.25$", "screen_jointaware_tiny_p025_g20_o8"),
    ]
    base = screening_values(RUNS_ROOT / (tiny[0][1] + "_seed{s}"), (0, 1, 2))
    lines += [r"\midrule", r"\multicolumn{6}{@{}l}{\emph{TinyLlama-1.1B, $s = 0.125$, $\lambda = 8$}} \\"]
    for k, (label, prefix) in enumerate(tiny):
        vals = screening_values(RUNS_ROOT / (prefix + "_seed{s}"), (0, 1, 2))
        diff = "--" if k == 0 else signed(st.mean(v - b for v, b in zip(vals, base)), 2)
        lines.append(f"{label} & 20 & & & {st.mean(vals):.2f} $\\pm$ {st.pstdev(vals):.2f} & {diff} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_screening.tex", "\n".join(lines) + "\n")


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", required=True)
    args = parser.parse_args(argv)
    out = Path(args.out)
    L = ledger()
    table_variants(out, L)
    H = horizon_values(L)
    table_horizon(out, H)
    figure_convergence(out, L)
    lx = table_operators(out)
    table_cost(out, L)
    table_screening(out)
    (out / "horizon_values.json").write_text(json.dumps(H, indent=2) + "\n", encoding="utf-8")
    print("wrote", sorted(p.name for p in out.iterdir()))
    print("LX crossover diagnostics:", lx)


if __name__ == "__main__":
    main()
