#!/usr/bin/env python3
"""Generate the LaTeX tables of thesis Section 6.4 (RQ3).

Inputs (all in this repository):
* ``results/exact_replays/replay_20261008/analysis/rq3_contrasts.csv`` (full-space
  interaction contrasts, written by ``scripts/analyze_exact_replays.py``);
* ``results/attribution/mistral_{qproj,attention_full}_seed{0,1,2}/attribution_matrix.csv``
  (screening replay matrices);
* the completed full-space final candidates (bit-widths next to removed sublayers).

Usage: python scripts/thesis_rq3_tables.py --out <thesis>/generated/rq3
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics as st
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
for path in (REPO, REPO / "scripts"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from plan_exact_replays import FULLSPACE_CANDIDATES  # noqa: E402
from src.exact_replay import load_final_candidate  # noqa: E402

CONTRASTS = REPO / "results/exact_replays/replay_20261008/analysis/rq3_contrasts.csv"
ATTRIBUTION = REPO / "results/attribution"
ATTN = ("q_proj", "k_proj", "v_proj", "o_proj")
MLP = ("gate_proj", "up_proj", "down_proj")
PAIR_LABEL = {"E3s1": "E3 s1", "DWs0": "DW s0", "J12s0": "J12 s0", "J12s1": "J12 s1", "J12s2": "J12 s2",
              "E3s0": "E3 s0", "E3s2": "E3 s2"}


def signed(x: float, d: int) -> str:
    return ("$+$" if x >= 0 else "$-$") + f"{abs(x):.{d}f}"


def write(out: Path, name: str, text: str) -> None:
    out.mkdir(parents=True, exist_ok=True)
    header = "% Generated by evopress/scripts/thesis_rq3_tables.py. Do not edit by hand.\n"
    (out / name).write_text(header + text, encoding="utf-8")


def table_fullspace(out: Path) -> None:
    rows = list(csv.DictReader(CONTRASTS.open(encoding="utf-8")))
    groups = [
        ("Shared-gene exchange, repair-free", lambda r: r["crossing"] == "shared-gene exchange" and r["repair"] == "repair-free"),
        ("Plain crossing of the same pairs, production repair", lambda r: r["crossing"].startswith("plain")),
        ("Shared-gene exchange, repair of exclusive genes", lambda r: r["crossing"] == "shared-gene exchange" and r["repair"] != "repair-free"),
    ]
    lines = [
        r"\begin{tabular}{@{}lrrrrrr@{}}", r"\toprule",
        r"& & \multicolumn{2}{c}{WikiText-2 log-PPL} & C4 log-PPL & \multicolumn{2}{c}{Calibration KL} \\",
        r"\cmidrule(lr){3-4}\cmidrule(lr){5-5}\cmidrule(l){6-7}",
        r"Pair & Repaired & $I$ & $(\delta_A, \delta_B)$ & $I$ & $I$ & $(\delta_A, \delta_B)$ \\",
    ]
    for title, keep in groups:
        lines += [r"\midrule", f"\\multicolumn{{7}}{{@{{}}l}}{{\\emph{{{title}}}}} \\\\"]
        for r in rows:
            if not keep(r):
                continue
            f = {k: float(r[k]) for k in ("w2_nll_I", "w2_nll_dA", "w2_nll_dB", "c4_nll_I", "kl_I", "kl_dA", "kl_dB")}
            pair = f"{PAIR_LABEL[r['a']]} $\\times$ {PAIR_LABEL[r['b']]}"
            lines.append(
                f"{pair} & {r['repaired_genes']} & {signed(f['w2_nll_I'], 3)} & "
                f"({signed(f['w2_nll_dA'], 3)}, {signed(f['w2_nll_dB'], 3)}) & {signed(f['c4_nll_I'], 3)} & "
                f"{signed(f['kl_I'], 4)} & ({signed(f['kl_dA'], 4)}, {signed(f['kl_dB'], 4)}) \\\\"
            )
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_fullspace_contrasts.tex", "\n".join(lines) + "\n")


def screening_rows():
    out = []
    for scope, label in (("qproj", "\\texttt{q\\_proj}"), ("attention_full", "attention")):
        for seed in range(3):
            path = ATTRIBUTION / f"mistral_{scope}_seed{seed}" / "attribution_matrix.csv"
            m = {(r["depth_label"], r["quant_label"]): r for r in csv.DictReader(path.open(encoding="utf-8"))}
            a, b = "standard_joint", "interaction_aware"
            row = {"scope": label, "seed": seed,
                   "rep_ab": int(m[(a, b)]["repair_num_changes"]), "rep_ba": int(m[(b, a)]["repair_num_changes"])}
            for metric, key in (("w2", "wiki2_ppl"), ("c4", "c4_ppl")):
                j = lambda d, q: math.log(float(m[(d, q)][key]))  # noqa: E731
                row[f"{metric}_dA"] = j(a, b) - j(a, a)
                row[f"{metric}_dB"] = j(b, a) - j(b, b)
                row[f"{metric}_I"] = -(row[f"{metric}_dA"] + row[f"{metric}_dB"])
                row[f"{metric}_uniA"] = j(a, "uniform3") - j(a, a)
                row[f"{metric}_uniB"] = j(b, "uniform3") - j(b, b)
            out.append(row)
    return out


def table_screening(out: Path) -> list[dict]:
    rows = screening_rows()
    lines = [
        r"\begin{tabular}{@{}llrrrrrr@{}}", r"\toprule",
        r"& & & \multicolumn{3}{c}{WikiText-2 log-PPL} & \multicolumn{2}{c}{Uniform 3-bit minus own} \\",
        r"\cmidrule(lr){4-6}\cmidrule(l){7-8}",
        r"Scope & Seed & Repaired & $I$ & $\delta_A$ & $\delta_B$ & mask $A$ & mask $B$ \\", r"\midrule",
    ]
    for k, r in enumerate(rows):
        if k == 3:
            lines.append(r"\midrule")
        scope = r["scope"] if r["seed"] == 0 else ""
        lines.append(
            f"{scope} & {r['seed']} & {r['rep_ab']}, {r['rep_ba']} & {signed(r['w2_I'], 3)} & {signed(r['w2_dA'], 3)} & "
            f"{signed(r['w2_dB'], 3)} & {signed(r['w2_uniA'], 3)} & {signed(r['w2_uniB'], 3)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_screening_contrasts.tex", "\n".join(lines) + "\n")
    return rows


def module(layer: int, proj: str) -> str:
    return f"model.layers.{layer}.{'self_attn' if proj in ATTN else 'mlp'}.{proj}"


def coupling_rows():
    rows = []
    for fam in ("J12", "E3"):
        for seed in range(3):
            cand = load_final_candidate(REPO / FULLSPACE_CANDIDATES[f"{fam}s{seed}"])
            e2 = load_final_candidate(REPO / FULLSPACE_CANDIDATES[f"E2s{seed}"])
            drop = cand["drop"]
            row = {"run": f"{fam} s{seed}"}
            for kind, projs, removed in (("mlp", MLP, "attn"), ("attn", ATTN, "mlp")):
                partner = [l for l in range(32) if drop[removed][l] and not drop[kind][l]]
                full = [l for l in range(32) if not drop[removed][l] and not drop[kind][l]]
                mean = lambda bits, layers: st.mean(bits[module(l, p)] for l in layers for p in projs)  # noqa: E731
                row[f"{kind}_n"] = len(partner)
                row[f"{kind}_partner"] = mean(cand["bits"], partner)
                row[f"{kind}_full"] = mean(cand["bits"], full)
                row[f"{kind}_e2_partner"] = mean(e2["bits"], partner)
                row[f"{kind}_e2_full"] = mean(e2["bits"], full)
            rows.append(row)
    return rows


def table_coupling(out: Path) -> list[dict]:
    rows = coupling_rows()
    lines = [
        r"\begin{tabular}{@{}lrrrrrrrr@{}}", r"\toprule",
        r"& \multicolumn{4}{c}{MLP projections} & \multicolumn{4}{c}{Attention projections} \\",
        r"\cmidrule(lr){2-5}\cmidrule(l){6-9}",
        r"& \multicolumn{2}{c}{Joint} & \multicolumn{2}{c}{E2, same layers} & \multicolumn{2}{c}{Joint} & \multicolumn{2}{c}{E2, same layers} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(l){8-9}",
        r"Run & rem. & kept & rem. & kept & rem. & kept & rem. & kept \\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            f"{r['run']} & {r['mlp_partner']:.2f} ({r['mlp_n']}) & {r['mlp_full']:.2f} & {r['mlp_e2_partner']:.2f} & "
            f"{r['mlp_e2_full']:.2f} & {r['attn_partner']:.2f} ({r['attn_n']}) & {r['attn_full']:.2f} & "
            f"{r['attn_e2_partner']:.2f} & {r['attn_e2_full']:.2f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "tab_coupling.tex", "\n".join(lines) + "\n")
    return rows


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", required=True)
    args = parser.parse_args(argv)
    out = Path(args.out)
    table_fullspace(out)
    screening = table_screening(out)
    coupling = table_coupling(out)
    (out / "values.json").write_text(json.dumps({"screening": screening, "coupling": coupling}, indent=2) + "\n",
                                     encoding="utf-8")
    print("wrote", sorted(p.name for p in out.iterdir()))


if __name__ == "__main__":
    main()
